from utils.cryptography.analyze import *

s = "UIZBH ZMNWP IZMZP IZDLZ MHHQG FDPIH XFQDP HDNDX HFOPI HKHNT HKMZR DMFOT ZMMNP ZMONX PZFDC ZDRBH TUZPI XFDPH CGPUI HDIHI HNKMT HXBNK NPZFD MUIZX IMFQD TMFEF NMPOQ BNDTH VPKNS NRNDP NDTWH PPIHW NKHEH WFDTX FCGNK ZMFDC FKHCF THKNP HPIND PIFMH NTSND XHTEW PIHXF CCFDH MPNQP IFKFO PIHXF CCFDH MPGIZ BFMFG IZXNB GKFRK NCCHZ DUIZX IPIHT FRCNP ZMPGK FOHMM HMPFT HCFDM PKNPH PIHMZ CGBHD NPQKH FOPIH MFQBF KPIHD HXHMM ZPWFO NGKZC NBEHZ DRMQX INTFR CNPZM PGKFC ZMHMP FHVPH DTIQC NDLDF UBHTR HEHWF DTPIH BZCZP MFOGF MMZEB HHVGH KZHDX HUIZB HZIQC EBWXF DOHMM PINPP IZMZM XFCGB HPHBW EHWFD TCWGF UHKZD MPHNT FONDW MQXIN PPHCG PZXFD OZDHC WMHBO PFPIH HVNCZ DNPZF DFOKH NMFDN BFDHN DTZPM GQKHP IFQRI PNDTZ TFDFP DHHTP FMHHL ONKOF KPIHM QCPFP NBFOZ PMXFR DZPZF DEHXN QMHZP INMZP MMHNP ZDCWF UDCZD TEHMZ THMXF CCFDB FRZXG KHMHD PMCHU ZPINX FCGBH PHNDT MWMPH CNPZX XNPNB FRQHF ONBBP IHMZC GBHFG HKNPZ FDMFO KHNMF DNDTZ PZMCW PNMLP FNDMU HKPIH JQHMP ZFDIF UONKK HNMFD XNDRF UZPIF QPPIH CNPHK ZNBGK HMHDP HTNDT PIHNZ TOQKD ZMIHT EWHVG HKZHD XH".replace(' ', '')

print(s)
print(s[::-1])

# quipqiup solves it

table = {
    'U': 'w',
    'I': 'h',
    'Z': 'i',
    'B': 'l',
    'H': 'e',
    'M': 's',
    'N': 'a',
    'W': 'y',

    'P': 't',
    'D': 'n',
    'F': 'o',
    'T': 'd',
    'X': 'c',
    'O': 'f',
    'Q': 'u',
    'K': 'r',
    'R': 'g',
    'L': 'k',
    'G': 'p',
    'C': 'm',
    'E': 'b',
    'V': 'x',
    'S': 'v',
    'J': 'q'
}
# print(len(set(s)))
# print(len(table))

s = replace_by_dict(s, table)

for i in range(1, 5):
    print(ngrams(s, i))
print(repeats(s, 2))

print(s.upper())