from itertools import permutations
from enchant import Dict

s = "ETREH EWRME NEADN AOEWN NOAAM LNALD EWROE YDLDD SRSEE EDHYT EWRRO DONHU TASHT OARST AEOST LMLPA TONAI TFOAO EBVTO RHIHE SEDWA LIHIT ETLBT SELAL NRUDO BTERH TISHM IATNT DKESL TWELE TYSHA OEMVY HETED SHTOA EFHMT EEWRN UELEB LTEIH ETLWT NOASM WHTAA ISHTW DENSA OHWRE HEWIA OTGWE ANHTT GHNIU ENLAP RTFOS RMESH LHUDO OESVR TEIWR SEEPR KRNLI IELTD STETL TASHR LAGIT NSEET TDNHI NEULS DIEIK NAODM ESHMT EEWRN EERSD ISDNE EBUOL EFHST SAEHM AAESD ITERH SHTAA ONWRD LEELW IPLSO BHDOE WOSIT DTAEH OERLP BLFLO TUATE OHTPE ESHMT OEDRN YOHTT GHUHO RTEEW UAOTB LAODS NAUCS ELHNE ORFRY OTOFW MTEHH EABAD BRSUD ETHLT LITET AWMNO DWSOA LUTEB USMCS DHLEO RREFH WAEAC VSOEC WRDIE RTWIH ENLSK HHRAE AIWSR RNALE IYHTW DENSA AHWLE RKDAE RTESH FTFLI EYHNW STEEH PPOLE EERWD RNATE OHHUE HSWEE ORDRE YOHWT TASAS NNIGD HITEN RDOWO HATEY UYASP NEADD SWIPH DEEAR GMNTO SHMEE SLEAV ASFFI DRITA MOOEC TFRHA XEXXR".split()


for perm in permutations(range(5)):
    # print(perm)

    res = []
    for line in s:
        res.append(['*'] * 5)
        for i in range(5):
            res[-1][perm[i]] = line[i]
    text = ''.join([''.join(line) for line in res])
    if text.startswith("THREE"):
        print(text)
        print(perm)
