s = "JHUDSTTRTUETT UAMUEHOTIRNTH NTECSEFHOPFEE CRSAOPAENOORS TEWTFORAHSRAE IGEIDLRCAENNR ORROIEICSAODE NEENSYVOBPTIF HTMWCOIUEOHFL AWYAOUNNEIIEE DHSSVMGTNNNEC FITNEAASTTGLT OCUERYTOHOCMI RHDGYRTFENOYO BIYLCEHTFWNHN IHDEOMEHAHTES DAACMENEVIRAH DDYTPMOVOCIRA EFAEOBRAUHBTV NENDSETRRTUGE MLDYERHIIHTLD YTNEDTPOTEEOI UAITTHAUESSWS NSGIHACSDOSWP CAHWETIVRUOIE LCTAWAFOELMTL EHASHHIYAMUHL TINPOICAMACAE OLDALSOGOYHND ADMSETCEFFTET LOYSOOESMIONH LNFIFRAWYXTTE OLAOOYNHEIRHA WEMNUOTIATAUG MAIARFHCRSNSI ERLTGARHLIQIT TNIEOLOHYNUAA OIALOLUAYTIST ENRYDTGVEELMI MGIFUHHEALLWO BTTONETBRLIHN AHYNCVHESESIW RAWDLOEEICECI KTIOEYSNHTTHT IMTFTAEMAUHEH NYHRHGAAVAELW AFTEOESDELMEH SAHAMSWEREIVI ETEDAMHIEYNAC AHMISAINAEDTH FEINLDCTDTAEI ARNGIEHHWHSSB RSCTBFSEIIAME IDRHROUPTSSEG NYEEARRRHETTA GIASRPROAXEON LNSEYUOSRPAHM IGEVMRUPDEDEY FIDOYPNEODYAL ENTLEODCUIPVE"

words = s.split()
ans = ""
for i in range(12,-1,-1):
    for word in words:
        ans += word[i]

print(ans)
