from string import ascii_lowercase

from utils.cryptography.analyze import ngrams, repeats, replace_by_dict
from enchant import Dict

s = "HEAAHEHEAANO HERCPKBBBBPKFF LQYURCAJGRRCFF GRBB NZVBPKLC HEGRBBBBPKFF USNOFFPKRC NZVBPK OUGRAIHE QSPKNOPKGRNZVB NZVBPK SAGRNZPKGRRCXMVB GRNOFF AJVBPKNO VBPK BBGRAJ NZVBPK HEGROUPK LQGRXMPK YULQ LQGRRCGRAIAARC VBPK XMGRUSSAVBNZ VBAABB QSRCPKGRNZVB AANZ AJGRBB NZVBPK LQGRXMPK YULQ YUNOPK AJVBYU VBGRBB QSPKPKNO GRBBBBGRAAOUPKFF QSLC GR SARCPKGRNZ LQPKGRRC YURC GRNOSAUSAABBVB QSUSNZ VBGRBB AIGRBBNZPKRCPKFF AANZ GRNOFF NOYUAJ AABB CRUSAAPKNZ HERCYUUSFF GRNOFF SARCGRIVPK VBPK BBNZYUYUFF LQYURC GR AIYUAIPKNONZ GRBB VBPK BBHEYUMLPK NZYU NZVBPK SAUSGRRCFF GRNOFF HEAAHEHEAANO SAGROZAANOSA GRNZ VBAAAI BBGRAJ VBYUAJ XMOUYUBBPKOULC VBPK RCPKBBPKAIQSOUPKFF VBAABB QSRCYUNZVBPKRC QSYURCYUAIAARC AJVBYUAI HEAAHEHEAANO VBGRFF OUAAMLPKFF LQRCYUAI NZVBPK LQAARCBBNZ GRFFAIAARCAANOSA NZVBPK SARCPKGRNZ AIGRNOBB OUYURCFFOULC QSUSNZ MLAANOFFOULC AIGRNONOPKRC LCPKNZ BBUSFFFFPKNOOULC LQYURC LQGRRCGRAIAARC VBAABB VBPKGRRCNZ AJGRBB BBNZRCGRNOSAPKOULC AIYUIVPKFF AJAANZVB GR LQPKPKOUAANOSA NZVBGRNZ VBPK VBGRFF NOYUNZ MLNOYUAJNO QSPKLQYURCPK VBPKRCPK AJGRBB YUNOPK AJAANZVB GRNO GRAARC YULQ VBAASAVB NOYUQSAAOUAANZLC BBUSXMVB GRBB GRRCGRSAYURCNO GRNZ NZAAAIPKBB RCPKIVPKGROUPKFF OUPKBBBB VBAASAVB HEPKRCVBGRHEBB LCPKNZ GROUBBYU OUPKBBBB AANOXMGROUXMUSOUGRQSOUPK GRNOFF RCPKAIYUNZPK YUNOPK YULQ NZVBPK MLAANOSABB YULQ AIPKNO QSYURCNO AANONZYU GR OUGRNZPKRC NZAAAIPK QSUSNZ NZYUUSXMVBPKFF AJAANZVB NZVBPK AJAABBFFYUAI GRNOFF BBGRFFNOPKBBBB YULQ NZVBPK PKOUFFPKRC RCGRXMPK VBPK MLNOPKAJ NOYUAJ AJVBLC QSPKRCPKSAYUNOFF BBHEYUMLPK VBAABB NOGRAIPK AJAANZVB OUYUIVPK VBPK AJGRBB GR XMGRHENZGRAANO NZVBGRNZ AIPKNO AJYUUSOUFF LQYUOUOUYUAJ NZVBGRNZ VBPK AJYUUSOUFF LQYUOUOUYUAJ PKIVPKNO USNOFFPKRC NZVBPK BBVBGRFFYUAJ YULQ NZVBPK QSOUGRXMML AJAANOSABB"
# s = s.replace('A', '')
# s = s.replace('B', '')
print(s)
s = s.replace(' ', '')
s = ' '.join([s[i:i+2] for i in range(0, len(s), 2)])
print(s)
for i in range(1, 5):
    print(len(ngrams(s,i)),ngrams(s, i))

print(repeats(s, 2))

digraphs = list(ngrams(s, 2).keys())
for digraph, ch in zip(digraphs, ascii_lowercase):
    s = s.replace(digraph, ch)
print(s.replace(' ', ''))


ans = "pippinpressedforwardastheypassedunderthelampbeneaththegatearchandwhenhesawthepalefaceoffaramirhecaughthisbreathitwasthefaceofonewhohasbeenassailedbyagreatfearoranguishbuthasmastereditandnowisquietproudandgravehestoodforamomentashespoketotheguardandpippingazingathimsawhowcloselyheresembledhisbrotherboromirwhompippinhadlikedfromthefirstadmiringthegreatmanslordlybutkindlymanneryetsuddenlyforfaramirhisheartwasstrangelymovedwithafeelingthathehadnotknownbeforeherewasonewithanairofhighnobilitysuchasaragornattimesrevealedlesshighperhapsyetalsolessincalculableandremoteoneofthekingsofmenbornintoalatertimebuttouchedwiththewisdomandsadnessoftheelderraceheknewnowwhyberegondspokehisnamewithlovehewasacaptainthatmenwouldfollowthathewouldfollowevenundertheshadowoftheblackwings"
print(ans.upper())