from utils.cryptography.analyze import *

s = "TTLHLORNMWFAVIMDSIALPRNITONEOREWURSNESCAUBTTMLRDANEPCSCIFNRMLESLANESAHEPIDIWATNEITWNSWODAAOEINNAUUEIATOITRUVRELHANENDOBEVENIESNHUATUENRSFMTLPWWTOOMIUTEAAHOPNDEYAITTSEONDNIDATTMGWABROKAAINSTLWRNDINRDFYTEDNINIFGAHDEFYTTAVKRNLIRHDTKGOTIEDLEOOBMREHYIMHWFDDLENIDESETKRTNFFSEATGCUHETEGCENFWEPEIFYSSOPERDCTABFNRGTTGPSNMOMINOHHNHOIDOUSIISHSETUCEPAONODETLRNYOEGNRKTYAEVEPGATTEASPOHHPLHIBDYBRHKNSDTEWSALSTATDERENLEEROAAOLWEONNTHEHNRTRDCTFAKENHWLNIOTEGMUSHOELHNTHLTTYDOIUREIDLAEENESNSEAOHEEANWTOTYANHYONASTUAILRFNNOICTNIDCHETOANESIOARIBDORUMEATODAIESDHTDDSHEOOIFHECWFONPOLKNEVRESEAVGHHTUESRETHSMSRAUONHAPKTSSGGAEHADPERAEVSHRMATDEEARENOROUAOSGPUHNALLSSSRHTRSDAILSRHMLNSNLTABOIAHDHIAEEPESLLFOTEOONRPELTARERSEERHRFAEEEDUBMAUAYOAAELHREPENAHTHOMEFDLLEHTHATNGAATTNWEOHENUSFSNSOTSIIHJGBNGOITCBATUNWLEHVERFOAHWNIERTULEIIHECNHNNALRLNESUCTPSOEAFHAELCCETBLHLAHDUUOLIHCHRENHAHHITOARLRCOOCHVPLHSAHGLLTSEHITEHDMWWTOTOEGENDESNIG"

print(ngrams(s, 1))
print(len(ngrams(s, 1)))
s = list(s)
s.sort()
s = ''.join(s)
print(s)

# print(find_factors(len(s)))  # [1, 902, 2, 451, 11, 41]

# 4 7 1 6 2 9 5 3 10 8 0
ans = "itwasalmostsunsetwhenthestonewallsswungofftheroadandhaltedinandaboutalittleorchardthelinesofanencampmentwhichwasintendedfornomorethananightsbivouacwerelaidoutandthemenunbuckledtheirstrapslaidofftheirpacksandsankthankfullytoeasefulpositionsofrestonthelonggrasswaitinguntilthetravelingcookerswhichontheirjourneyalongtheroadhadbeenpreparingtheeveningmealwerebroughtupanddischargedoftheirsavorycontentsbutbeforethemealwasservedtherecameanunpleasantinterruptionwhichbodedillforthesafetyofthenightscampaheavyshellrushedoverheaddroppedinthefieldaboutfourhundredyardsbeyondthecampburstwithacrashandagushofevilblacksmokeaflyingtorrentofsplintersandupflungearthwhilethemenwerestillwatchingtheslowdispersaloftheshellsmokeandpassingcommentsuponhowneartothemwasthelineithadtakenanotherandanothershellwhoopedovertheminaprolongedlineonthefieldsbeyondweseemsaidlarryarundeltohavechosenamightyunhealthypositionthisnight"
print(ans.upper())